main:
    path: /
    controller:  App\Controller\MainController::home
    
add:
    path: /
    controller:  App\Controller\ArticleController::add
    
list:
    path: /
    controller:  App\Controller\ArticleController::list

connexion:
    path: /
    controller:  App\Controller\UserController::login

